### ISSUE TITLE
Day14課題 develop(blog実装)→masterにマージ　※チームリーダーtask

### ISSUE THREAD

**Issue by dsaa151562000** [dive-into-code-suzuki/achive03#10]
## タスク
- [x]    最新developをローカルにpull
- [x]    最新developをmasterにmerge
- [x]    最新masterをpush

**Comment by konchanxxx** [comment]
issueはクローズしても見れるので大丈夫ですよ！
開発は小さいタスクでもcloseしていくことが重要なので可能なものはcloseしていったほうが良いと思います。

**Comment by dsaa151562000** [comment]
近藤さん

了解いたしました！
クローズします
